version: "3.8"

services:
  web:
    image: ghcr.io/ferilee/web-iinfibriastuti:latest
    ports:
      - "3016:3016"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/sqlite.db
    volumes:
      - ./data:/data
    restart: always
