version: "3.8"

services:
  web:
    image: ghcr.io/ferilee/web-iinfibriastuti:latest
    ports:
      - "3016:3016"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/sqlite.db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/data
    restart: always
